#!/bin/bash

################################################################
# Create 9 equally sized panes in tmux
################################################################

# Check if session name was provided
if [ -z "$1" ]; then
    echo "Usage: $0 <session_name>"
    exit 1
fi

session_name=$1

# Start tmux session
tmux new-session -d -s "$session_name"

# Split window into three horizontal panes
tmux split-window -h
tmux split-window -h

# Move to the first pane and split it vertically into three panes
tmux select-pane -t "$session_name.0"
tmux split-window -v
tmux split-window -v

# Move to the second pane and split it vertically into three panes
tmux select-pane -t "$session_name.3"
tmux split-window -v
tmux split-window -v

# Move to the third pane and split it vertically into three panes
tmux select-pane -t "$session_name.6"
tmux split-window -v
tmux split-window -v

# Set pane sizes
tmux select-layout tiled

# Attach to the tmux session
tmux attach-session -t "$session_name"
