#!/bin/bash

################################################################
# Create 4 equally sized panes in tmux
################################################################

# Check if session name was provided
if [ -z "$1" ]; then
    echo "Usage: $0 <session_name>"
    exit 1
fi

session_name=$1

# Start tmux session
tmux new-session -d -s "$session_name"

# Split window into two horizontal panes
tmux split-window -h

# Move to the first pane and split it vertically into three panes
tmux select-pane -t "$session_name.0"
tmux split-window -v

# Move to the second pane and split it vertically into three panes
tmux select-pane -t "$session_name.2"
tmux split-window -v

# Attach to the tmux session
tmux attach-session -t "$session_name"
